language: node_js
node_js:
  - "0.10"
  
before_script:
  - npm install
  - sed -i s/describe\(\'getLastTag\'/xdescribe\(\'getLastTag\'/ test/test.js
  - sed -i s/describe\(\'updateVersionFile/xdescribe\(\'updateVersionFile/ test/test.js
  - sed -i s/describe\(\'run/xdescribe\(\'run/ test/test.js
  - sed -i s/describe(\'releaseNewTag/describe(\'xreleaseNewTag/ test/test.js

